version: '3'

services:
  main:
    build:
      context: ./
    ports:
      - "4000:3115"
    env_file:
      - .env.prod
    networks:
      - mynetwork
  catalog:
    build:
      context: ./microservices/catalog-service
    depends_on:
      - mongodb
    env_file:
      - .env.prod
    networks:
      - mynetwork

  auth:
    build:
      context: ./microservices/auth-service
    depends_on:
       - mongodb
    env_file:
      - .env
    networks:
      - mynetwork
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${TYPEORM_DB_NAME}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
  redis:
    image: redis:latest
    networks:
      - mynetwork
    ports:
      - "8389:6379"

  mongodb:
    image: mongo:latest
    env_file:
      - .env.prod
    networks:
      - mynetwork
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork

  nginx:
    build: ./proxy/
    ports:
      - "80:80"
    depends_on:
      - main
      - auth
      - catalog
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
  mongodb_data:
