version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "57017:27017"
    volumes:
      - mongo_data:/data/db

  mysqldb:
    image: mysql:8
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=online_shop
      - MYSQL_USER=gevorg
      - MYSQL_PASSWORD=passord
    ports:
      - "5306:3306"
volumes:
  mongo_data:
  mysql_data: