name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  CI:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Force install dependencies
      run: npm ci --force

    - name: Build
      run: npm run build --if-present

    - name: Test
      run: npm test

